### ISSUE TITLE
great chart , easy to use and working. just update seems lacking

### ISSUE THREAD

**Issue by heavyair** [snowPu/ngx-beautiful-charts#6]
Hello,

I tried to append new data to ganttChartData, but seems angular not reflect changes.   is the data binding not working ? 

below is a method I created inside the demo of  gantChartData

  public OnClick() {

    console.log("on Click");

    this.ganttChartData.push(

      {
        name: 'Market Team',
        timelines: {
          'Market Research': [
            {from: 'July 28, 2019', to: 'September 20, 2019', info: 'wtv'}
            
          ],
          'User Documentation': [
            {from: 'August 10, 2019', to: 'September 15, 2019', info: 'wtv'}
          ]
        }
      }
    );

  }

**Comment by snowPu** [comment]
Hi @heavyair !
Thanks for your kind feedback! :)

The charts do track updates to data. Unfortunately, Angular Change Detection tracks only object identity and not object content. Thus a push to an array doesn't record as a change. The same would happen in case of an angular mat-table. 

You could do the following so that angular detects it as a change and forces the ngOnChanges method that is defined in the component:

```
 this.ganttChartData.push(
  {
    name: 'Test Team B',
    timelines: {
      'Market Research': [
        {from: 'July 28, 2019', to: 'September 20, 2019', info: 'wtv'}
        
      ],
      'User Documentation': [
        {from: 'August 10, 2019', to: 'September 15, 2019', info: 'wtv'}
      ]
    }
  }
 );
this.ganttChartData = this.ganttChartData.slice();
```
